name    'brucem-solr'
version '0.0.1'
source 'git@github.com:brucem/puppet-solr.git'
author 'Bruce Morrison'
license 'Apache License, Version 2.0'
summary 'Solr Module'
description 'A puppet module for managing Solr installation and configuration'
project_page 'https://github.com/brucem/puppet-solr'
dependency 'puppetlabs/java', '>= 0.3.0'
